### ISSUE TITLE
when detect folder based on local KB, the client will raise bad_json-xxxx.txt

### ISSUE THREAD

**Issue by superkaiy** [scanoss/ldb#11]
When I tried to scan local folder based on the local KB, the client will raise exceptions as following:
- Scanning |                                | 0/76ERROR: The SCANOSS API returned an invalid JSON: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
- Scanning |####                            | 11/76ERROR: The SCANOSS API returned an invalid JSON: Expecting ',' delimiter or '}': line 1 column 9006 (char 9005)
![Screenshot from 2023-06-19 17-08-04](https://github.com/scanoss/ldb/assets/45934483/39d42323-b304-4d3d-95f7-d3af19c7136f)
![Screenshot from 2023-06-19 17-11-29](https://github.com/scanoss/ldb/assets/45934483/101473ee-0c0f-4f10-b2fd-14c2895f4ee4)

I found the exceptions returned from API server is related to the functions in the file src/hex.c
- ldb_uint32_read
- ldb_uint40_read
- ldb_uint16_read
![Screenshot from 2023-06-19 17-19-02](https://github.com/scanoss/ldb/assets/45934483/7cbb4191-8443-4afb-8767-80a44aab440e)

The print of the warnings will be returned/reponsed as data embedded in the result with format json. So how can we handle with it?

**Comment by mscasso-scanoss** [comment]
Hello @superkaiy, thank you for reporting this issue. You are correct; a new version of LDB will be released soon, and we will take your suggestion into consideration, along with many other improvements and new features. However, a missing sector is not expected behavior, so I recommend that you double-check the consistency of your knowledge base. Please don't hesitate to ask any other questions or make any additional requests.

**Comment by superkaiy** [comment]
@mscasso-scanoss Thanks for your replication. I double-confirmed about my KB
1. tide up my knowledge base, and tide up the storage
2. do mining process again
then I scanned my local target folder on the first time, it will throw the similar exceptions as following:
`return an invalid JSON (JSONDecodeError - xxx): Expecting ',' delimiter: line 1 column 8439 (char 8438)`
but when I tried to scan the folder at the second time, it became normal without no exceptions.
There is some loss data in the first output data, and the second output data is completed.
Could you help to give me some suggestions for me to follow up the exceptions?

**Comment by superkaiy** [comment]
@mscasso-scanoss , I found the cause why the table url data will increase during scanning process. We fetch the data via ldb_fetch_recordset function, and ldb sector is opend with mode 'r+', it will try to new a sector or a file when it does not exist

![Screenshot from 2023-07-06 10-44-39](https://github.com/scanoss/ldb/assets/45934483/26a61fc1-a794-41d5-8504-91cf3febb40e)

**Comment by DRong1121** [comment]
[superkaiy](https://github.com/superkaiy)Hi, may I ask how did you tide up your KB when you have encountered a "cannot read LDB sector" error?

**Comment by superkaiy** [comment]
@DRong1121 For it's just on the phase of trial run, I delete whole database via command `rm -rf <ldb root>/<database name>`.
I guess it is necessary to build up a replication mechanism or version control management on the KB

**Comment by mscasso-scanoss** [comment]
Hello @superkaiy, thank you very much for your feedback. I wanted to let you know that the release of ldb will be published soon, and your suggestions will be taken into consideration. Please feel free to test it out and take a look at the latest changes on this branch: https://github.com/scanoss/ldb/tree/ldb_upgrade.

**Comment by superkaiy** [comment]
> Hello @superkaiy, thank you very much for your feedback. I wanted to let you know that the release of ldb will be published soon, and your suggestions will be taken into consideration. Please feel free to test it out and take a look at the latest changes on this branch: https://github.com/scanoss/ldb/tree/ldb_upgrade.

I meet a "cannot read LDB sector" error only during scanning process, and I found a weird thing that the some ldb sector will be re-written during the scanning process. I guess the exception is related to the re-written operations for there is no exception during mining process. so maybe change the mode "r+" to "r" in ldb_open function will be helpful to you.
![Screenshot from 2023-07-06 10-44-39](https://github.com/scanoss/ldb/assets/45934483/2900aba5-384d-47a6-84e5-597c04381429)
