### ISSUE TITLE
How to specify the LENGTH parameter in merge command

### ISSUE THREAD

**Issue by leoliaolei** [scanoss/ldb#32]
When executing merge command `merge DBNAME/TABLENAME1 into DBNAME/TABLENAME2 max LENGTH`, how to set value for parameter `LENGTH`?

**Comment by mscasso-scanoss** [comment]
Hi @leoliaolei,

LENGTH is simply a reference for the maximum expected size of the records. For example, if you set LENGTH=1024, any record longer than 1024 bytes will be ignored during the merge.

Best regards, and sorry for the delay.
